apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
    component: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        component: keycloak
    spec:
      volumes:
      - name: keycloak-volume
        configMap:
          name: apicurio-realm-configmap
      containers:
        - name: keycloak
          image: >-
            quay.io/keycloak/keycloak:21.1.1
          args: [ "start --import-realm" ]
          volumeMounts:
            - name: keycloak-volume
              mountPath: /opt/keycloak/data/import
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
          # https://www.keycloak.org/server/all-config
          - name: KEYCLOAK_ADMIN
            valueFrom:
              secretKeyRef:
                name: keycloak-credentials
                key: username
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-credentials
                key: password
          - name: KC_PROXY
            value: edge
          - name: KC_HOSTNAME_STRICT
            value: 'false'
          - name: KC_PROXY
            value: edge
          
          # Logging, Health and Metrics
          - name: KC_LOG_LEVEL
            value: INFO
          - name: KC_HEALTH_ENABLED
            value: 'true'
          - name: KC_METRICS_ENABLED
            value: 'true'

          # Custom Env Variables
          - name: KEYCLOAK_DATABASE
            valueFrom:
              secretKeyRef:
                name: rds-keycloak-credentials
                key: database
          - name: KEYCLOAK_DATASOURCE_PORT
            valueFrom:
              secretKeyRef:
                name: rds-keycloak-credentials
                key: port
          - name: KEYCLOAK_DATASOURCE_HOST
            valueFrom:
              secretKeyRef:
                name: rds-keycloak-credentials
                key: host

          # Datsource Configurations
          - name: KC_DB
            value: postgres
          - name: KC_DB_URL
            value: "jdbc:postgresql://${KEYCLOAK_DATASOURCE_HOST}:${KEYCLOAK_DATASOURCE_PORT}/${KEYCLOAK_DATABASE}"
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: rds-keycloak-credentials
                key: user
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rds-keycloak-credentials
                key: password
          - name: KC_TRANSACTION_XA_ENABLED
            value: 'true'
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            privileged: false
