apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
spec:
  target:
    name: keycloak-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-apicurio
  refreshInterval: 1m0s
  data:
    - secretKey: username
      remoteRef:
        key: kubernetes/dev-eng-apicurio/apicurio/keycloak-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: kubernetes/dev-eng-apicurio/apicurio/keycloak-credentials
        property: password