apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-keycloak-credentials
spec:
  target:
    name: rds-keycloak-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-apicurio
  refreshInterval: 1m0s
  data:
    - secretKey: database
      remoteRef:
        key: kubernetes/dev-eng-apicurio/apicurio/dev-eng-apicurio-rds-pgsql-keycloak-credentials
        property: database
    - secretKey: host
      remoteRef:
        key: kubernetes/dev-eng-apicurio/apicurio/dev-eng-apicurio-rds-pgsql-keycloak-credentials
        property: host
    - secretKey: port
      remoteRef:
        key: kubernetes/dev-eng-apicurio/apicurio/dev-eng-apicurio-rds-pgsql-keycloak-credentials
        property: port
    - secretKey: user
      remoteRef:
        key: kubernetes/dev-eng-apicurio/apicurio/dev-eng-apicurio-rds-pgsql-keycloak-credentials
        property: user
    - secretKey: password
      remoteRef:
        key: kubernetes/dev-eng-apicurio/apicurio/dev-eng-apicurio-rds-pgsql-keycloak-credentials
        property: password
