apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: postgres-connector0
  labels:
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: ${secrets:rhaf-apicurio/rds-apicurio-registry-client-application-credentials:host}
    database.port: ${secrets:rhaf-apicurio/rds-apicurio-registry-client-application-credentials:port}
    database.user: ${secrets:rhaf-apicurio/rds-apicurio-registry-client-application-credentials:user}
    database.password: ${secrets:rhaf-apicurio/rds-apicurio-registry-client-application-credentials:password}
    database.dbname: ${secrets:rhaf-apicurio/rds-apicurio-registry-client-application-credentials:database}
    plugin.name: "pgoutput"
    topic.prefix: "server1"
    schema.include.list: "inventory"
    key.converter: "io.apicurio.registry.utils.converter.AvroConverter"
    key.converter.apicurio.registry.url: "https://apicurio-registry-api-rhaf-apicurio.apps.dev-eng-ocp4-mas.dev.3sca.net"
    key.converter.apicurio.registry.auto-register: "true"
    key.converter.apicurio.registry.find-latest: "true"
    key.converter.apicurio.registry.use-id: "contentId"
    key.converter.apicurio.registry.as-confluent: "true"
    key.converter.apicurio.auth.client.id: ${secrets:rhaf-apicurio/probe-application-credentials:client-id}
    key.converter.apicurio.auth.client.secret: ${secrets:rhaf-apicurio/probe-application-credentials:client-secret}
    key.converter.apicurio.auth.service.token.endpoint: "https://keycloak-rhaf-apicurio.apps.dev-eng-ocp4-mas.dev.3sca.net/realms/apicurio/protocol/openid-connect/token"
    value.converter.apicurio.auth.client.id: ${secrets:rhaf-apicurio/probe-application-credentials:client-id}
    value.converter.apicurio.auth.client.secret: ${secrets:rhaf-apicurio/probe-application-credentials:client-secret}
    value.converter.apicurio.auth.service.token.endpoint: "https://keycloak-rhaf-apicurio.apps.dev-eng-ocp4-mas.dev.3sca.net/realms/apicurio/protocol/openid-connect/token"
    value.converter: "io.apicurio.registry.utils.converter.AvroConverter"
    value.converter.apicurio.registry.url: "https://apicurio-registry-api-rhaf-apicurio.apps.dev-eng-ocp4-mas.dev.3sca.net"
    value.converter.apicurio.registry.auto-register: "true"
    value.converter.apicurio.registry.find-latest: "true"
    value.converter.apicurio.registry.as-confluent: "true"
    value.converter.apicurio.registry.use-id: "contentId"
    schema.name.adjustment.mode: "avro"
    field.name.adjustment.mode: "avro"