apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: postgres-connector0
  labels:
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: ${secrets:apicurio/rds-apicurio-registry-client-application-credentials:host}
    database.port: ${secrets:apicurio/rds-apicurio-registry-client-application-credentials:port}
    database.user: ${secrets:apicurio/rds-apicurio-registry-client-application-credentials:user}
    database.password: ${secrets:apicurio/rds-apicurio-registry-client-application-credentials:password}
    database.dbname: ${secrets:apicurio/rds-apicurio-registry-client-application-credentials:database}
    heartbeat.interval.ms: "1000"
    plugin.name: "pgoutput"
    topic.prefix: "server1"
    schema.include.list: "inventory"
    key.converter: "io.apicurio.registry.utils.converter.AvroConverter"
    key.converter.apicurio.registry.url: "https://registry-api.dev.apicur.io/apis/registry/v3"
    key.converter.apicurio.registry.auto-register: "true"
    key.converter.apicurio.registry.find-latest: "true"
    key.converter.apicurio.registry.auth.client.id: ${secrets:apicurio/probe-application-credentials:client-id}
    key.converter.apicurio.registry.auth.client.secret: ${secrets:apicurio/probe-application-credentials:client-secret}
    key.converter.apicurio.registry.auth.service.token.endpoint: "https://sso.dev.apicur.io/realms/apicurio/protocol/openid-connect/token"
    value.converter.apicurio.registry.auth.client.id: ${secrets:apicurio/probe-application-credentials:client-id}
    value.converter.apicurio.registry.auth.client.secret: ${secrets:apicurio/probe-application-credentials:client-secret}
    value.converter.apicurio.registry.auth.service.token.endpoint: "https://sso.dev.apicur.io/realms/apicurio/protocol/openid-connect/token"
    value.converter: "io.apicurio.registry.utils.converter.AvroConverter"
    value.converter.apicurio.registry.url: "https://registry-api.dev.apicur.io/apis/registry/v3"
    value.converter.apicurio.registry.auto-register: "true"
    value.converter.apicurio.registry.find-latest: "true"
    schema.name.adjustment.mode: "avro"
    field.name.adjustment.mode: "avro"