apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: probe-application-credentials
spec:
  target:
    name: probe-application-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-mas
  refreshInterval: 1m0s
  data:
    - secretKey: client-id
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/apicurio-probe-application
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/apicurio-probe-application
        property: client-secret

    - secretKey: database
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/dev-eng-mas-apicurio-rds-pgsql-apicurio-registry-client-credentials
        property: database
    - secretKey: host
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/dev-eng-mas-apicurio-rds-pgsql-apicurio-registry-client-credentials
        property: host
    - secretKey: port
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/dev-eng-mas-apicurio-rds-pgsql-apicurio-registry-client-credentials
        property: port
    - secretKey: user
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/dev-eng-mas-apicurio-rds-pgsql-apicurio-registry-client-credentials
        property: user
    - secretKey: password
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/dev-eng-mas-apicurio-rds-pgsql-apicurio-registry-client-credentials
        property: password
