apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-designer
    component: apicurio-designer-api
  name: apicurio-designer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apicurio-designer-api
  template:
    metadata:
      labels:
        app: apicurio-designer
        component: apicurio-designer-api
    spec:
      containers:
        - image: >-
            quay.io/apicurio/apicurio-api-designer@sha256:4ff5d8b9b5482d45703362496aa49cdc0bb870b97a31a663b80ddbfe3eaec2b7
          name: apicurio-designer-api
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: DESIGNER_LOG_LEVEL
              value: DEBUG
            - name: DESIGNER_ACCESS_LOG_ENABLE
              value: 'true'
            - name: QUARKUS_PROFILE
              value: prod
            - name: DESIGNER_CORS_ALLOWED_ORIGINS
              value: '*'
            - name: AUTH_ENABLED
              value: 'true'
            - name: OIDC_TOKENT_ENDPOINT
              value: >-
                https://keycloak-rhaf-apicurio.apps.dev-eng-ocp4-mas.dev.3sca.net/realms/apicurio
            - name: OIDC_URL
              value: >-
                https://keycloak-rhaf-apicurio.apps.dev-eng-ocp4-mas.dev.3sca.net/realms/apicurio
            - name: OIDC_API_CLIENT_ID
              value: designer-api
            - name: APICURIO_STORAGE_DB_KIND
            - name: "postgresql"
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-designer-credentials
                  key: database
            - name: DESIGNER_DATASOURCE_PORT
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-designer-credentials
                  key: port
            - name: DESIGNER_DATASOURCE_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-designer-credentials
                  key: host
            - name: APICURIO_DATASOURCE_URL
              value: >-
                jdbc:postgresql://${DESIGNER_DATASOURCE_HOST}:${DESIGNER_DATASOURCE_PORT}/${DESIGNER_DATABASE}
            - name: APICURIO_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-designer-credentials
                  key: user
            - name: APICURIO_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-designer-credentials
                  key: password
          resources:
            limits:
              cpu: 400m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /apis/designer/v0/system/info
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /apis/designer/v0/system/info
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

