apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-designer
    component: apicurio-designer-ui
  name: apicurio-designer-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apicurio-designer-ui
  template:
    metadata:
      labels:
        app: apicurio-designer
        component: apicurio-designer-ui
    spec:
      containers:
        - image: >-
            quay.io/apicurio/apicurio-api-designer-ui@sha256:0d5524aad665f1d1f72562e601421111a160bef9c167ba6844fd147f1c7c089c
          name: apicurio-designer-ui
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: DESIGNER_API_URL
              value: 'https://designer-api.dev.apicur.io/apis/designer/v0'
            - name: DESIGNER_AUTH_TYPE
              value: oidc
            - name: DESIGNER_AUTH_URL
              value: 'https://sso.dev.apicur.io/realms/apicurio'
            - name: DESIGNER_AUTH_CLIENT_ID
              value: designer-ui
            - name: DESIGNER_AUTH_REDIRECT_URL
              value: 'https://designer.dev.apicur.io/'
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          livenessProbe:
            httpGet:
              path: /config.js
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /config.js
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

