apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-designer
    component: apicurio-designer-ui
  name: apicurio-designer-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apicurio-designer-ui
  template:
    metadata:
      labels:
        app: apicurio-designer
        component: apicurio-designer-ui
    spec:
      containers:
        - image: >-
            quay.io/apicurio/apicurio-studio-ui@sha256:d2a8491c45d1b5cb101add078d26a99f5677efccef08f939656a7f512fef052a
          name: apicurio-designer-ui
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: APICURIO_DESIGNER_API_URL
              value: 'https://designer-api.dev.apicur.io/apis/designer/v0'
            - name: APICURIO_AUTH_TYPE
              value: oidc
            - name: APICURIO_AUTH_URL
              value: 'https://sso.dev.apicur.io/realms/apicurio'
            - name: APICURIO_AUTH_CLIENT_ID
              value: designer-ui
            - name: APICURIO_AUTH_REDIRECT_URL
              value: 'https://designer.dev.apicur.io/'
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          livenessProbe:
            httpGet:
              path: /config.js
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /config.js
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

