apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-designer
    component: apicurio-designer-api
  name: apicurio-designer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apicurio-designer-api
  template:
    metadata:
      labels:
        app: apicurio-designer
        component: apicurio-designer-api
    spec:
      containers:
        - image: >-
            quay.io/apicurio/apicurio-api-designer@sha256:8a86755ce9019a685cc536bbedd11cf7917bb1c2a9612291553ece653c77a5e0
          name: apicurio-designer-api
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: APICURIO_LOG_LEVEL
              value: DEBUG
            - name: QUARKUS_HTTP_ACCESS-LOG_ENABLED
              value: 'true'
            - name: QUARKUS_PROFILE
              value: prod
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: '*'
            - name: QUARKUS_OIDC_TENANT-ENABLED
              value: 'true'
            - name: QUARKUS.OIDC.TOKEN-PATH
              value: 'https://sso.dev.apicur.io/realms/apicurio'
            - name: QUARKUS.OIDC.AUTH-SEVER-URL
              value: 'https://sso.dev.apicur.io/realms/apicurio'
            - name: QUARKUS.OIDC.CLIENT-ID
              value: designer-api
            - name: APICURIO_STORAGE_DB_KIND
              value: postgresql
            - name: APICURIO_DATASOURCE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-designer-credentials
                  key: database
            - name: APICURIO_DATASOURCE_PORT
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-designer-credentials
                  key: port
            - name: APICURIO_DATASOURCE_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-designer-credentials
                  key: host
            - name: APICURIO_DATASOURCE_URL
              value: >-
                jdbc:postgresql://${APICURIO_DATASOURCE_HOST}:${APICURIO_DATASOURCE_PORT}/${APICURIO_DATASOURCE_DATABASE}
            - name: APICURIO_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-designer-credentials
                  key: user
            - name: APICURIO_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-designer-credentials
                  key: password
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /apis/designer/v0/system/info
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /apis/designer/v0/system/info
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

