apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-registry
    component: apicurio-registry-api
  name: apicurio-registry-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apicurio-registry-api
  template:
    metadata:
      labels:
        app: apicurio-registry
        component: apicurio-registry-api
    spec:
      containers:
        - image: >-
            quay.io/apicurio/apicurio-registry-sql@sha256:e464260f35856497ec84cb57e43dc81e522261ef2e33fe8c7262a336187f90de
          name: apicurio-registry-api
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: AUTH_ENABLED
              value: 'true'
            - name: KEYCLOAK_URL
              value: >-
                https://keycloak-rhaf-apicurio.apps.dev-eng-ocp4-mas.dev.3sca.net/
            - name: KEYCLOAK_REALM
              value: apicurio
            - name: KEYCLOAK_API_CLIENT_ID
              value: registry-api
            - name: REGISTRY_LOG_LEVEL
              value: DEBUG
            - name: LOG_LEVEL
              value: DEBUG
            - name: QUARKUS_PROFILE
              value: prod
            - name: REGISTRY_CONFIG_CACHE_ENABLED
              value: 'true'
            - name: CORS_ALLOWED_ORIGINS
              value: '*'
            - name: REGISTRY_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-registry-credentials
                  key: database
            - name: REGISTRY_DATASOURCE_PORT
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-registry-credentials
                  key: port
            - name: REGISTRY_DATASOURCE_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-registry-credentials
                  key: host
            - name: REGISTRY_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-registry-credentials
                  key: user
            - name: REGISTRY_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-apicurio-registry-credentials
                  key: password
            - name: REGISTRY_DATASOURCE_URL
              value: >-
                jdbc:postgresql://${REGISTRY_DATASOURCE_HOST}:${REGISTRY_DATASOURCE_PORT}/${REGISTRY_DATABASE}
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 400Mi

