apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-studio
    component: apicurio-studio-ui
  name: apicurio-studio-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apicurio-studio-ui
  template:
    metadata:
      labels:
        app: apicurio-studio
        component: apicurio-studio-ui
    spec:
      containers:
        - image: >-
            quay.io/apicurio/apicurio-studio-ui@sha256:7e6b4faf996b7be88df7f512d7377194c0968ed8eb667c0f01d58552c712d5ee
          name: apicurio-studio-ui
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: APICURIO_STUDIO_API_URL
              value: 'https://studio-api.dev.apicur.io/apis/studio/v1'
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          livenessProbe:
            httpGet:
              path: /config.js
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /config.js
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

