apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-apicurio-studio-credentials
spec:
  target:
    name: rds-apicurio-studio-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-mas
  refreshInterval: 1m0s
  data:
    - secretKey: database
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/dev-eng-mas-apicurio-rds-pgsql-apicurio-studio-credentials
        property: database
    - secretKey: host
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/dev-eng-mas-apicurio-rds-pgsql-apicurio-studio-credentials
        property: host
    - secretKey: port
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/dev-eng-mas-apicurio-rds-pgsql-apicurio-studio-credentials
        property: port
    - secretKey: user
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/dev-eng-mas-apicurio-rds-pgsql-apicurio-studio-credentials
        property: user
    - secretKey: password
      remoteRef:
        key: kubernetes/dev-eng-mas/rhaf-apicurio/dev-eng-mas-apicurio-rds-pgsql-apicurio-studio-credentials
        property: password
