---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.6.0
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  build:
    output:
      type: docker
      image: image-registry.openshift-image-registry.svc:5000/rhaf-apicurio/debezium-connect:latest
    plugins:
      - name: debezium-connector-postgres
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.3.3.Final/debezium-connector-postgres-2.3.3.Final-plugin.tar.gz
            sha512sum: a67963e1088c99db1e38a85c68507c171054b7238447f5aa1fe2cbdd55946d498c030b4b82dc005d55cd23a7cded0494d8fff0fdc59c4787098fe590bddb2990
          - type: tgz
            url: https://repo1.maven.org/maven2/io/apicurio/apicurio-registry-distro-connect-converter/2.3.1.Final/apicurio-registry-distro-connect-converter-2.3.1.Final.tar.gz
            sha512sum: eee79c68bae272bef6f720fa5af6b583ed16cc2c5aa2da96e464b99ade677abd290561b97d3d9279ed158da216a78d15aa4f9495614517915b6eac29b13cfb56
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["rds-apicurio-registry-client-application-credentials", "probe-application-credentials"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector-configuration-role-binding
subjects:
  - kind: ServiceAccount
    name: kafka-connect-cluster-connect
    namespace: rhaf-apicurio
roleRef:
  kind: Role
  name: connector-configuration-role
  apiGroup: rbac.authorization.k8s.io