apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: strimzi
spec:
  targetNamespaces:
    - rhaf-apicurio
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
spec:
  channel: stable
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic