apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    run: postgres
spec:
  containers:
    - name: postgres
      image: quay.io/debezium/example-postgres:2.6
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: probe-application-credentials
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: probe-application-credentials
              key: password
        - name: POSTGRES_DB
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    run: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    run: postgres