name: Verify Registry Deployment (3scale-dev)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:

  verify-registry:
    name: Verify 3scale Registry Deployment
    runs-on: ubuntu-latest
    if: github.repository_owner == 'apicurio'
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Code Checkout
        run: |
          mkdir repo
          cd repo
          git init
          git config --global user.name "apicurio-ci"
          git config --global user.email "apicurio.ci@gmail.com"
          git remote add origin "https://apicurio-ci:${{ secrets.ACCESS_TOKEN }}@github.com/Apicurio/apicurio-3scale-gitops.git"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull

      - name: Run e2e tests
        run: |
          cd repo/tests/registry
          npm install
          npx playwright install --with-deps

          export REGISTRY_URL=${{ secrets.REGISTRY_URL }}
          export TEST_USERNAME=${{ secrets.TEST_USERNAME }}
          export TEST_PASSWORD=${{ secrets.TEST_PASSWORD }}
          npm run test

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: repo/tests/registry/playwright-report/
          retention-days: 3

      - name: Slack Notification (Always)
        if: always()
        run: |
          MESSAGE="Nightly Registry integration tests passed successfully."
          REPO="${{ github.repository }}"
          LINK="https://github.com/$REPO/actions/runs/${{ github.run_id }}"
          PAYLOAD="{\"workflow\": \"${{ github.workflow }}\", \"status\": \"${{ job.status }}\", \"message\": \"$MESSAGE\", \"link\": \"$LINK\", \"repository\": \"$REPO\"}"
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" ${{ secrets.SLACK_NOTIFICATION_WEBHOOK }}

      - name: Slack Notification (Error)
        if: failure()
        run: |
          MESSAGE="Nightly Registry integration tests FAILED."
          REPO="${{ github.repository }}"
          LINK="https://github.com/$REPO/actions/runs/${{ github.run_id }}"
          PAYLOAD="{\"workflow\": \"${{ github.workflow }}\", \"status\": \"${{ job.status }}\", \"message\": \"$MESSAGE\", \"link\": \"$LINK\", \"repository\": \"$REPO\"}"
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" ${{ secrets.SLACK_ERROR_WEBHOOK }}
